name: Markdown Lint

on:
  push:
    branches: [main]
    paths:
      - '**/*.md'
      - '.github/workflows/markdown-lint.yml'
  pull_request:
    paths:
      - '**/*.md'
      - '.github/workflows/markdown-lint.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
            !profile/README.md
          config: '.github/markdownlint.json'
