name: Update Profile README

on:
  schedule:
    - cron: '0 0 * * *' # Ejecutar todos los días a medianoche
    - cron: '*/5 * * * *' # Ejecutar cada 5 minutos

  workflow_dispatch: # Permite ejecutar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'
          enable-cache: true
          cache-dependency-glob: 'scripts/actualizar_readme.py'

      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UV_SYSTEM_PYTHON: 1
        run: uv run scripts/actualizar_readme.py

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add profile/README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: actualizar README del perfil [skip ci]"
          git push
